---

apiVersion: v1
kind: Service
metadata:
  name: frontend-master
spec:
  selector:
    app: frontend-master
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  frontend-master
spec:
  selector:
    matchLabels:
      app: frontend-master
      tier: frontend
      track: stable
  replicas:  
  template:
    metadata:
      labels:
        app: frontend-master
        tier: frontend
        track: stable
    spec:
      containers:
      - name: frontend-master
        image: hellorings.azurecr.io/samiyaakhtar/hello-world-full-stack-frontend:master-20200603.13
        imagePullPolicy: IfNotPresent
        env:
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: REACT_APP_BACKEND_URL
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]


